# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-ecs
version: 0.0
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-resources.html#reference-appspec-file-structure-resources-ecs
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:117645918752:task-definition/cdkcodeworkshopecsbluegreendeploystackcodeDeployTaskDef16FC7A58:2"
        LoadBalancerInfo:
          ContainerName: "amazonSample"
          ContainerPort: 80
#        PlatformVersion: "[Version number, ex: 1.3.0]"
#        NetworkConfiguration:
#          AwsvpcConfiguration:
#            Subnets: ["SubnetId1","SubnetId2"]
#            SecurityGroups: ["ecs-security-group-1"]
#            AssignPublicIp: "ENABLED-or-DISABLED"
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-ecs
Hooks:
  # - BeforeInstall: "BeforeInstallHookLambdaFunctionName"
  # - AfterInstall: "AfterInstallHookLambdaFunctionName"
  # - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:117645918752:function:cdk-code-workshop-ecs-blue-green--Function76856677-y24JcYrrwGYL"
  # - BeforeAllowTraffic: "SanityTestHookLambdaFunctionName"
  # - AfterAllowTraffic: "ValidationTestHookLambdaFunctionName"